### ISSUE TITLE
# Backend Routes

### ISSUE THREAD

**Issue by Evan-Leon** [Alyx-Clark/OurTube#6]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in snake_case
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
- Ex. probably don't need a GET likes api endpoint because that info comes through the post show

**Comment by Evan-Leon** [comment]
- try and avoid nested routes (ex. POST to create a comment nested under video, can just have with its own POST to api/comments) likely you will have access to the video id and the front end and can pass it directly (no need to get it as a wildcard on the backend)
  - Additionally when you get a video you can bring up it's associated likes, views and comments (and can get rid of those individual routes)
  - same with likes (should have its own dedicated routes (POST/DELETE)
Good work!

**Comment by moodln** [comment]
Looks good! It looks like you're missing a wildcard for your `PATCH` route for `users` - but that's it!
